### ISSUE TITLE
slow / not multithreaded

### ISSUE THREAD

**Issue by toddmedema** [clineamb/gulp-s3-upload#11]
Been getting complaints from my team that this is much slower than the old plugin we were using (gulp-s3) and, looking at the source, I think I have an idea why - are they multithreaded and this one isn't? Their code uses event-stream and map to split out the uploads to do multiple at once. Is that something you'd consider implementing?

https://github.com/nkostelnik/gulp-s3/blob/master/index.js

**Comment by clineamb** [comment]
This one is not multi-threaded, since when I initially built it, I needed to just bust something out quickly.  

I will definitely consider adding this soon!

**Comment by clineamb** [comment]
I'll close this issue, since @thomaswelton [added the pull request](https://github.com/clineamb/gulp-s3-upload/pull/14).

(:
