### ISSUE TITLE
file_counts Object is not declared/instantiated. 

### ISSUE THREAD

**Issue by marioatlp** [clineamb/gulp-s3-upload#18]
ReferenceError: file_counts is not defined
    at /Users/.../node_modules/gulp-s3-upload/index.js:42:13

this appears to have been introduced in this commit 
https://github.com/clineamb/gulp-s3-upload/commit/c712cef357ee1bf3731806be95482906d0c4050a

**Comment by nebstrebor** [comment]
Also seeing this...

**Comment by clineamb** [comment]
Fixed just now. It was queued up to be pushed, the other night.
