### ISSUE TITLE
PR caused ContentEncoding to break

### ISSUE THREAD

**Issue by confuser** [clineamb/gulp-s3-upload#23]
Referring to #22 

This breaks setting a `ContentEncoding` option as the variable `contentEncoding` is only ever set if manualContentEncoding is defined. If not, it overrides `objOpts.ContentEncoding` regardless of if `contentEncoding` is a falsey value.

https://github.com/clineamb/gulp-s3-upload/blob/master/index.js#L169

**Comment by jdrydn** [comment]
:clap: With regards to the versioning too :cry:

**Comment by clineamb** [comment]
Thanks for this! I'll take a look at it after work today.  Should be an easy fix -- the check for ContentEncoding is set and NOT manualContentEncoding.

**Comment by clineamb** [comment]
I fixed this issue in the latest 1.3.0 tag/release.  This also inspired a new `maps` option.

Thanks guys!
