### ISSUE TITLE
    S3 Error: null

### ISSUE THREAD

**Issue by eddyLazar** [clineamb/gulp-s3-upload#24]
Error when uploading files to bucket containing dots(like example.com)

**Comment by clineamb** [comment]
This might be an error with the AWS-SDK, since the plugin does 0 manipulation to the bucket name.

Can I get a snippet of your setup just to be sure?

**Comment by eddyLazar** [comment]
So, is there a hope this will be accomplished somehow through plugin settings?

**Comment by clineamb** [comment]
Short answer: Yes.

While this is the Ruby SDK, the issues are similar in this thread: https://forums.aws.amazon.com/thread.jspa?threadID=151763

**Comment by clineamb** [comment]
I just uploaded 1.4.0/1.4.1 (I had a bad typo to bug fix and some hanging dev console logs for 1.4.1).

This update exposes the [S3 Constructor](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property) options.  I have been working out on what options will exactly fix your particular issue, but hopefully different configurations can be tested to see what is going on.

If you manage to find a config solution before I do, please share!

**Comment by eddyLazar** [comment]
It seems to be a common problem. http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**When using virtual hosted–style buckets with SSL, the SSL wild card certificate only matches buckets that do not contain periods. To work around this, use HTTP or write your own certificate verification logic.**

So, http protocol has to be specified in constructor

**Comment by clineamb** [comment]
I think we'll have to wait until (if ever) the AWS packages get updated to handle this better, since I don't think writing the cert verification logic is not within the scope of this plugin.  

The `httpOptions` is available to you in the S3 constructor, so that is the best option we have here in an attempt to fix this case.

Closing this out.
