### ISSUE TITLE
Doesn't work anymore because of upgrade of hasha 

### ISSUE THREAD

**Issue by tyruk** [clineamb/gulp-s3-upload#25]
this library no longer work because signature of hasha.fromFile changed - it no longer accept callback, but returns promise instead.

**Comment by clineamb** [comment]
Gotcha, fix coming later today

**Comment by kohey18** [comment]
:+1:

**Comment by clineamb** [comment]
Fixed! Went with synchronously hasha-ing the `file._contents` buffer.
