### ISSUE TITLE
maps - shared mutable options

### ISSUE THREAD

**Issue by iofjuupasli** [clineamb/gulp-s3-upload#26]
```js
gulp.src('./**')
  .pipe(s3({
    maps: {
      ContentDisposition: function (keyname) { return keyname; }
    }
  }));
```

It send files with value from latest file. Probably because it overrides `options.ContentDisposition` on each file.

The solution might be to make a copy of options for each file.

**Comment by clineamb** [comment]
I don't seem to understand what the exact problem is in particular. Can you elaborate a bit more?

**Comment by iofjuupasli** [comment]
One of files which I upload to S3 named `fileOne`. So `ContentDisposition` should be `fileOne`. But on S3 I see `Content-Disposition` is `fileTwo`, which also uploading to S3.

Hope this information is enough.

But also after quick research in code I found this line
https://github.com/clineamb/gulp-s3-upload/blob/master/index.js#L133
which makes mutation to shared object. And then async task execution:
https://github.com/clineamb/gulp-s3-upload/blob/master/index.js#L155

I'm not sure whether it is the reason of bug.

**Comment by clineamb** [comment]
Ah, gotcha. This is probably the reason. I'll just move the maps into there -- that should fix it.

**Comment by clineamb** [comment]
https://github.com/clineamb/gulp-s3-upload/commit/1831deca4b9d362c651956490553ffdedca009b4

This latest commit should be the fix.
