### ISSUE TITLE
Parameter name

### ISSUE THREAD

**Issue by lucasdupin** [clineamb/gulp-s3-upload#27]
The README says the parameter name is *accessKeySecret* but actually it should be *secretAccessKey*

![screen shot 2015-10-19 at 6 39 59 pm](https://cloud.githubusercontent.com/assets/88702/10590704/efac9526-7690-11e5-9fb4-008368d5d6f3.png)

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Credentials.html

**Comment by clineamb** [comment]
Thanks for noting this -- I'll be sure to fix it soon!
