### ISSUE TITLE
using profiles from ~/.aws

### ISSUE THREAD

**Issue by dkebler** [clineamb/gulp-s3-upload#32]
I use multiple profiles in my ~.aws/credentials file.  Easy to use in the aws-cli.

But not understanding your comment ""you can specify the profile name inline with the call to gulp."

Are you talking about gulp.task? or  in the require statment?

Example of this usage would be helpful here and in the documentation.

Thx.

**Comment by clineamb** [comment]
Hm, I think my Readme got mixed up in some merge things. It's the code block line another line below.

```
AWS_PROFILE=myprofile gulp
```

So, you'd just type `AWS_PROFILE=myprofile gulp upload`, for example.

**Comment by dkebler** [comment]
Ok I get it.

Alternatively if your readme said.

"If you want to use an AWS profile in your ~/.aws/credentials file just set
the environment variable AWS_PROFILE with your profile name before invoking
your gulp task."

that would have been clear (to me at least.)

On Mon, Nov 23, 2015 at 11:22 AM, Caroline A. <notifications@github.com>
wrote:

> Closed #32 <https://github.com/clineamb/gulp-s3-upload/issues/32>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clineamb/gulp-s3-upload/issues/32#event-472443919>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by clineamb** [comment]
I'll make sure to update the line. The feature was a contribution, and I left what the author had written at the time in the readme as-is, but I'll be sure to revise everything soon.  Thanks for the feedback! (:
