### ISSUE TITLE
Overriding ContentType

### ISSUE THREAD

**Issue by kaiwah** [clineamb/gulp-s3-upload#35]
I noticed on the docs that it says ContentType does not need to be defined, and the plugin will filter out any attempts at changing it. 

But for files where I have gzip compression, I need to set the Content-Type to "application/javascript" and "text/css" for ".jz.gz" and ".css.gz" respectively.

Can this be done at all with gulp-s3-upload

**Comment by kaiwah** [comment]
By default, all .gz extensions end up with "application/octet-stream" as the Content-Type which completely breaks the parsing

**Comment by kaiwah** [comment]
Nevermind I'm stupid, completely missed the mimeTypeLookup functionality. Closing this.

**Comment by clineamb** [comment]
@kaiwah No worries, let me know if I can help with anything else! (:
