### ISSUE TITLE
Adding support for custom Keys

### ISSUE THREAD

**Issue by subinsebastien** [clineamb/gulp-s3-upload#36]
This is necessary since, in uses cases like, uploading multiple resized versions of images into an s3 bucket, a rename system wont work, since gulp will add its own key. Just need the key filtering removed.

**Comment by clineamb** [comment]
You could do a check with the [`keyTransform` method](https://github.com/clineamb/gulp-s3-upload#keytransform-nametransform). Also, if I'm inferring correctly, this use-case is the one you reference in #37?  If so, I would do the resizing first and have a separate upload task read from the folder that the resized images are being saved to.  The `gulp-s3-upload` gulp plugin uses the relative file name unless the `keyTransform` method is overwritten.

Check out [these lines](https://github.com/clineamb/gulp-s3-upload/blob/master/index.js#L46-L69) in the source code for some reference on what is being sent through to the `keyTransform` method.

**Comment by clineamb** [comment]
@subinsebastien Did you ever find a solution to this?
