### ISSUE TITLE
contentEncoding = null results in contentEncoding `gzip`

### ISSUE THREAD

**Issue by matiasdecarli** [clineamb/gulp-s3-upload#42]
I'm running into some issues regarding compression. I'm using `contentEncoding` to see which files should be marked in the metadata as gzipped, like this

```
gulp.task('uploadToS3', function() {
  var expires = new Date();
  expires.setUTCFullYear(2020);

  return pump([
      gulp.src('./dist/**'),
      s3({
          Bucket: process.env.S3_BUCKET,
          ACL:    'public-read',
          Expires: expires,
          manualContentEncoding: function(keyname) {
              var contentEncoding = null;

              if (keyname=='index.html') contentEncoding = 'gzip'
              if (keyname=='js/scripts.js') contentEncoding = 'gzip'
              if (keyname=='css/css.css') contentEncoding = 'gzip'

              return contentEncoding;
          }
        },{
          maxRetries: 5
      })
    ]);
});
```

This results is some files outside that range (for example files in `img` folder), uploaded with:

![screen shot 2016-11-08 at 4 23 00 pm](https://cloud.githubusercontent.com/assets/2442390/20113569/a91a12f4-a5cf-11e6-9c5e-31ec3e616969.png)

This is not the excpected behaivour, right?

I'll do more digging tonight in order to debug the request to `AWS`

PS: I'm using version `"1.6.1"`

**Comment by clineamb** [comment]
Hrm, it may be something wrong with that old `keyname`. Try using the [map.ParamName style](https://github.com/clineamb/gulp-s3-upload#mapsparamname-) to apply ContentEncoding.

Also, while I don't see that you're transforming the `keyname`, I would make sure that the `keyname `you're expecting is matching your cases (which I'm sure you've done, but putting this here to be sure).

**Comment by matiasdecarli** [comment]
Hi @clineamb, thanks for the quick reply!

Yes, I've tried that very same thing doing `console.log(keyname, contentEncoding)` and the result was something like this

```
...
index.html gzip
css/css.css gzip
js/scripts.js gzip
img/img1.svg null
img/img2.svg null
...
```

So... that points me into think that's a issue on the request. Apparently once a file is under the `gzip` encoding, all the other files ends on the same request

**Comment by clineamb** [comment]
I may know what the problem is then. Expect a fix w/in the next 2 days, but it is probably coming from some bad variable setting.

**Comment by matiasdecarli** [comment]
Great! Thanks a lot @clineamb. Let me know if I can help you with something

**Comment by clineamb** [comment]
@matiasdecarli I added a fix, and this bug also exposed that something similar could happen to the other `maps.ParamName` function mappers, so I also took care of those.
