### ISSUE TITLE
Error: S3 headObject Error: Error: connect EHOSTUNREACH 169.254.169.254:80

### ISSUE THREAD

**Issue by MichaelJCole** [clineamb/gulp-s3-upload#45]
Hi, I went to update a site and got this error:

```
Error: S3 headObject Error: Error: connect EHOSTUNREACH 169.254.169.254:80
```

That IP is a [dynamically reserved link-local IP](https://serverfault.com/questions/427018/what-is-this-ip-address-169-254-169-254) - which I don't completely understand, but is reserved as non-routable.

Do you know why it's trying to connect to an unreachable IP?  

Thanks in advance!

**Comment by MichaelJCole** [comment]
Ok, I fixed this by installing the aws cli and configuring it.

More or less:
```
pip install --upgrade --user awscli
aws configure   
./deploy.sh
```

**Comment by clineamb** [comment]
👍
