### ISSUE TITLE
Security issue with event-stream@3.3.6

### ISSUE THREAD

**Issue by rbeeger** [clineamb/gulp-s3-upload#59]
There is a security issue with event-stream@3.3.6 https://github.com/dominictarr/event-stream/issues/116#issuecomment-441759047

You might want to pin your dependency on version 3.3.4 or look into upgrading to 4.x.

**Comment by ERPedersen** [comment]
You can close this now that 1.7.1 has been published.

**Comment by rbeeger** [comment]
Thanks. Fixed in #60
