### ISSUE TITLE
Is there a way to pass in AWS SDK config into gulp-s3-upload?

### ISSUE THREAD

**Issue by chrisyeung1121** [clineamb/gulp-s3-upload#9]
?

**Comment by clineamb** [comment]
I think you need to elaborate a little bit. 

As per the docs, everything in the [AWS Config Constructor](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property) are available when you initialize gulp-s3-upload like so:

```js
var s3 = require('gulp-s3-upload')({
        accessKeyId:        "YOUR DEV ID",
        secretAccessKey:    "YOUR SECRET"
    });
```

You can pass options like `region`, `httpOptions`, etc. in this constructor.  If you want to pass a config file through (like a json file), you can do the following:

```js
var s3config = require('./s3config.js');
var s3 = require('gulp-s3-upload')(s3config);
```

where `s3config.js` looks something like this...
```js
module.exports = {
    'accessKeyId': "YOUR DEV ID",
    'secretAccessKey': "YOUR SECRET",
    // etc...
};
```

Or, if you want to use a module like [config](https://github.com/lorenwest/node-config) (where your config settings are in something like a `.yaml` file):

```js
var s3config = require('config').AWS;
var s3 = require('gulp-s3-upload')(s3config);
```

I can help you better if you explain further, but this is what is currently available.
